build_name           = "firewall"
vm_id                = 900
vm_name              = "pfsense-CE-2.6"
iso_file             = "pfSense-CE-2.6.0.iso"
template_description = "Firewall pfSense template with the default configuration generated by Packer on {{ isotime `2006-01-02` }}."

network_adapters = {
  "01" = {
    # WAN
    bridge   = "vmbr0"
    model    = "virtio"
    vlan_tag = ""
    firewall = false
  }
}
