---
- name: "Ensure the VM trusts the HomeLab's CA Certificate."
  ansible.builtin.import_tasks: "roles/common/tasks/freebsd/os/trust-ca-certificate.yml"

- name: "Installing required packages"
  ansible.builtin.import_tasks: "installing-packages.yml"

- name: "Removing unnecessary packages"
  ansible.builtin.import_tasks: "removing-packages.yml"

- name: "Removing unnecessary files, folders and configuration"
  ansible.builtin.import_tasks: "roles/common/tasks/freebsd/os/clean-up.yml"
