---
- name: "Adding the {{ user_password_id }} user in the pfsense config.xml"
  pfsensible.core.pfsense_user:
    name: "{{ user_password_id }}"
    password: "{{ user_password_encrypted }}"
    descr: "{{ user_password_id }}"
    scope: "system"
    groups: ["admins"]
    priv: ['page-all', "user-shell-access"]
    state: "present"

- name: "Allowing the user to run any commands with sudo without the need to type its password"
  community.general.sudoers:
    name: "{{ user_password_id }}"
    user: "{{ user_password_id }}"
    sudoers_path: "/usr/local/etc/sudoers.d"
    commands: "ALL"
    runas: "ALL"
    nopassword: true
    state: "present"

- name: "Removing the admin user"
  pfsensible.core.pfsense_user:
    name: "admin"
    state: "absent"
  ignore_errors: true
